### PR TITLE
[v1.07][PPC] Fix build since 40374121b8b1

### LINKED ISSUE #350: Linux PPC: `make` fails
Compiler output:
```
cc -Wall -Wextra -pedantic -DARCH_PPC -std=gnu99 -fstack-protector-all -Wno-language-extension-token -O2 -Wfloat-equal -Wshadow -Wpointer-arith -Wstrict-prototypes -DGIT_FULL_VERSION=\""v1.06-39-ga0c0"\" src/common/main.c src/common/cpu.c src/common/udev.c src/common/printer.c src/common/args.c src/common/global.c src/common/freq.c src/ppc/ppc.c src/ppc/uarch.c src/ppc/udev.c -o cpufetch
src/ppc/ppc.c: In function 'get_topology_info':
src/ppc/ppc.c:87:23: warning: comparison of integer expressions of different signedness: 'uint32_t' {aka 'unsigned int'} and 'int' [-Wsign-compare]
   87 |     if (topo->sockets == UNKNOWN_DATA) {
      |                       ^~
At top level:
cc1: note: unrecognized command-line option '-Wno-language-extension-token' may have been intended to silence earlier diagnostics
src/ppc/udev.c: In function 'fill_array_from_sys':
src/ppc/udev.c:16:10: error: 'name' undeclared (first use in this function)
   16 |   memset(name, 0, sizeof(char) * 128);
      |          ^~~~
src/ppc/udev.c:16:10: note: each undeclared identifier is reported only once for each function it appears in
At top level:
cc1: note: unrecognized command-line option '-Wno-language-extension-token' may have been intended to silence earlier diagnostics
make: *** [Makefile:126: cpufetch] Error 1

```
It looks like it was broken in commit 40374121b8b1397112c925b024e8a61c062357aa, simply renaming `name` to `path` makes it build and run.

### PR DESCRIPTION
**Pull request by MingcongBai**
Since commit 40374121b8b1 ("[v1.06] Replace emalloc+memset with ecalloc when possible. Refactor some memory allocation code"), variable `path' was erroneously renamed as `name' in the call to `memset()'.

Rename it back to `path' to fix build.

Fixes #350, #360.

### CODE REVIEW

**Comment by MingcongBai** [comment]
Build tested on a ppc64el build host:

https://buildit.aosc.io/logs/121144-cpufetch-1.07-ppc64el-Kevin-2025-11-02-18:17:25.txt
