### ISSUE TITLE
Linux PPC: `make` fails

### ISSUE THREAD

**Issue by kala-telo** [Dr-Noob/cpufetch#350]
Compiler output:
```
cc -Wall -Wextra -pedantic -DARCH_PPC -std=gnu99 -fstack-protector-all -Wno-language-extension-token -O2 -Wfloat-equal -Wshadow -Wpointer-arith -Wstrict-prototypes -DGIT_FULL_VERSION=\""v1.06-39-ga0c0"\" src/common/main.c src/common/cpu.c src/common/udev.c src/common/printer.c src/common/args.c src/common/global.c src/common/freq.c src/ppc/ppc.c src/ppc/uarch.c src/ppc/udev.c -o cpufetch
src/ppc/ppc.c: In function 'get_topology_info':
src/ppc/ppc.c:87:23: warning: comparison of integer expressions of different signedness: 'uint32_t' {aka 'unsigned int'} and 'int' [-Wsign-compare]
   87 |     if (topo->sockets == UNKNOWN_DATA) {
      |                       ^~
At top level:
cc1: note: unrecognized command-line option '-Wno-language-extension-token' may have been intended to silence earlier diagnostics
src/ppc/udev.c: In function 'fill_array_from_sys':
src/ppc/udev.c:16:10: error: 'name' undeclared (first use in this function)
   16 |   memset(name, 0, sizeof(char) * 128);
      |          ^~~~
src/ppc/udev.c:16:10: note: each undeclared identifier is reported only once for each function it appears in
At top level:
cc1: note: unrecognized command-line option '-Wno-language-extension-token' may have been intended to silence earlier diagnostics
make: *** [Makefile:126: cpufetch] Error 1

```
It looks like it was broken in commit 40374121b8b1397112c925b024e8a61c062357aa, simply renaming `name` to `path` makes it build and run.

**Comment by MingcongBai** [comment]
Fix submitted here for your reference - https://github.com/Dr-Noob/cpufetch/pull/376
